// src/api/_mockData.ts
// 모든 엔티티에 대한 종합 더미데이터
import type {
  User,
  Team,
  Project,
  Sprint,
  Issue,
  Server,
  Service,
  Deployment,
} from 'src/types/models.types';
import type { DashboardStats } from 'src/api/dashboard.api';

const now = new Date();
const date = (daysOffset: number): string => {
  const d = new Date(now);
  d.setDate(d.getDate() + daysOffset);
  return d.toISOString();
};

// --- 유저 ---
export const mockUsers: User[] = [
  {
    id: 1,
    authentik_id: 'user_1_auth',
    email: 'dev@devflow.com',
    username: 'dev_user',
    full_name: '개발자 (테스트)',
    phone: null,
    is_active: true,
    is_admin: false,
    avatar_url: null,
    created_at: date(-30),
    updated_at: date(-5),
  },
  {
    id: 2,
    authentik_id: 'user_2_auth',
    email: 'admin@devflow.com',
    username: 'admin_user',
    full_name: '관리자 (테스트)',
    phone: null,
    is_active: true,
    is_admin: true,
    is_superuser: true,
    avatar_url: null,
    created_at: date(-50),
    updated_at: date(-1),
  },
];

// --- 팀 ---
export const mockTeams: Team[] = [
  {
    id: 1,
    name: '코어 개발팀',
    description: '핵심 백엔드 및 인프라를 담당하는 팀',
    owner_id: 2,
    is_active: true,
    created_at: date(-30),
    updated_at: date(-10),
  },
  {
    id: 2,
    name: '프론트엔드팀',
    description: 'Vue.js 기반 UI/UX 개발',
    owner_id: 1,
    is_active: true,
    created_at: date(-25),
    updated_at: date(-5),
  },
];

// --- 프로젝트 ---
export const mockProjects: Project[] = [
  {
    id: 1,
    name: 'DevFlow ERP 고도화',
    key: 'DEV',
    description:
      '기존 ERP 시스템에 칸반 보드 및 배포 기능 추가. 이 설명은 여러 줄로 표시될 수 있으며, 카드에서는 2줄로 잘려야 합니다.',
    team_id: 1,
    status: 'active',
    start_date: date(-30),
    end_date: date(60),
    repository_url: 'https://github.com/user/devflow-erp',
    created_at: date(-40),
    updated_at: date(-1),
  },
  {
    id: 2,
    name: '신규 모바일 앱 (D-Project)',
    key: 'DPROJ',
    description: '신규 고객을 위한 모바일 앱 개발',
    team_id: 2,
    status: 'planning',
    start_date: date(10),
    end_date: date(100),
    repository_url: 'https://github.com/user/d-project',
    created_at: date(-20),
    updated_at: date(-2),
  },
  {
    id: 3,
    name: '레거시 시스템 유지보수',
    key: 'LEGACY',
    description: '기존 ASP.NET 기반 시스템 유지보수',
    team_id: 1,
    status: 'on_hold',
    start_date: date(-100),
    end_date: null,
    repository_url: null,
    created_at: date(-200),
    updated_at: date(-10),
  },
];

// --- 스프린트 ---
export const mockSprints: Sprint[] = [
  {
    id: 1,
    name: '스프린트 #1 - 칸반보드 UI',
    project_id: 1,
    goal: '칸반보드 기본 UI 및 드래그앤드롭 기능 구현',
    status: 'active',
    start_date: date(-7),
    end_date: date(7),
    total_issues: 3,
    completed_issues: 1,
    created_at: date(-10),
    updated_at: date(-1),
  },
  {
    id: 2,
    name: '스프린트 #2 - 배포 파이프라인 연동',
    project_id: 1,
    goal: '배포 관리 페이지 및 API 연동',
    status: 'planning',
    start_date: date(8),
    end_date: date(22),
    total_issues: 0,
    completed_issues: 0,
    created_at: date(-5),
    updated_at: date(-5),
  },
  {
    id: 3,
    name: '모바일 앱 디자인',
    project_id: 2,
    goal: 'Figma 디자인 완료',
    status: 'active',
    start_date: date(-5),
    end_date: date(9),
    total_issues: 1,
    completed_issues: 0,
    created_at: date(-6),
    updated_at: date(-1),
  },
];

// --- 이슈 ---
export const mockIssues: Issue[] = [
  {
    id: 1,
    title: '[FEAT] 칸반 보드 페이지 생성',
    description: 'vuedraggable을 사용한 기본 칸반 보드 UI를 생성합니다.',
    project_id: 1,
    sprint_id: 1,
    type: 'task',
    status: 'in_progress',
    priority: 'high',
    assignee_id: 1,
    reporter_id: 2,
    story_points: 5,
    due_date: date(5),
    created_at: date(-6),
    updated_at: date(-1),
  },
  {
    id: 2,
    title: '[BUG] 로그인 페이지에서 SSO 버튼이 보이지 않음',
    description: '환경 변수가 로드되지 않아 SSO 버튼이 렌더링되지 않는 문제 수정',
    project_id: 1,
    sprint_id: 1,
    type: 'bug',
    status: 'done',
    priority: 'urgent',
    assignee_id: 1,
    reporter_id: 2,
    story_points: 2,
    due_date: date(-3),
    created_at: date(-5),
    updated_at: date(-3),
  },
  {
    id: 3,
    title: '[FEAT] 이슈 상세 페이지 구현',
    description: '이슈 목록에서 클릭 시 상세 정보를 볼 수 있는 페이지 구현 (신규)',
    project_id: 1,
    sprint_id: 1,
    type: 'story',
    status: 'todo',
    priority: 'medium',
    assignee_id: null,
    reporter_id: 2,
    story_points: 8,
    due_date: null,
    created_at: date(-2),
    updated_at: date(-2),
  },
  {
    id: 4,
    title: '[DESIGN] 모바일 앱 로고 디자인',
    description: 'D-Project에 사용할 로고 시안 3종',
    project_id: 2,
    sprint_id: 3,
    type: 'task',
    status: 'todo',
    priority: 'low',
    assignee_id: 2,
    reporter_id: 1,
    story_points: 3,
    due_date: date(7),
    created_at: date(-4),
    updated_at: date(-4),
  },
  {
    id: 5,
    title: '[REFACTOR] API 클라이언트 정리',
    description: '인터셉터 로직 개선 및 에러 핸들링 보강',
    project_id: 1,
    sprint_id: 2,
    type: 'improvement',
    status: 'todo',
    priority: 'medium',
    assignee_id: 1,
    reporter_id: 2,
    story_points: 3,
    due_date: null,
    created_at: date(-1),
    updated_at: date(-1),
  },
];

// --- 서버 ---
export const mockServers: Server[] = [
  {
    id: 1,
    name: 'Dev-WAS-01',
    description: '개발 환경 웹서버 (Ubuntu 22.04)',
    hostname: 'dev-was-01.internal',
    ip_address: '10.0.1.10',
    environment: 'development',
    type: 'web',
    status: 'running',
    os_type: 'Ubuntu',
    os_version: '22.04',
    cpu_cores: 4,
    memory_gb: 16,
    disk_gb: 100,
    created_at: date(-40),
    updated_at: date(0),
  },
  {
    id: 2,
    name: 'Prod-DB-01',
    description: '운영 환경 메인 데이터베이스 (PostgreSQL)',
    hostname: 'prod-db-01.internal',
    ip_address: '192.168.1.50',
    environment: 'production',
    type: 'database',
    status: 'error',
    os_type: 'Debian',
    os_version: '11',
    cpu_cores: 8,
    memory_gb: 64,
    disk_gb: 500,
    created_at: date(-50),
    updated_at: date(-1),
  },
  {
    id: 3,
    name: 'Stg-Web-01',
    description: '스테이징 환경 웹서버',
    hostname: 'stg-web-01.internal',
    ip_address: '10.0.2.20',
    environment: 'staging',
    type: 'web',
    status: 'stopped',
    os_type: 'Ubuntu',
    os_version: '22.04',
    cpu_cores: 2,
    memory_gb: 8,
    disk_gb: 50,
    created_at: date(-30),
    updated_at: date(-5),
  },
];

// --- 서비스 ---
export const mockServices: Service[] = [
  {
    id: 1,
    name: 'DevFlow ERP (API)',
    description: '메인 ERP 백엔드 API',
    server_id: 1,
    type: 'api',
    status: 'running',
    version: '1.2.3',
    port: 8000,
    url: 'http://10.0.1.10:8000',
    process_name: 'devflow-api',
    pid: 12345,
    container_id: 'container-id-123',
    image_name: 'devflow-api:1.2.3',
    cpu_limit: 1,
    memory_limit_mb: 1024,
    health_check_url: 'http://10.0.1.10:8000/api/v1/health',
    health_check_enabled: true,
    environment_variables: { NODE_ENV: 'development' },
    config_path: '/app/config.prod.json',
    log_path: '/var/log/devflow-api.log',
    auto_start: true,
    notes: '개발 서버에서 실행 중인 메인 API',
    created_at: date(-30),
    updated_at: date(0),
  },
  {
    id: 2,
    name: 'Prod Database (PostgreSQL)',
    description: '운영 DB',
    server_id: 2,
    type: 'database',
    status: 'failed',
    version: '14.5',
    port: 5432,
    url: null,
    process_name: 'postgres',
    pid: 1234,
    container_id: null,
    image_name: null,
    cpu_limit: null,
    memory_limit_mb: null,
    health_check_url: null,
    health_check_enabled: false,
    environment_variables: null,
    config_path: null,
    log_path: null,
    auto_start: true,
    notes: 'DB 서버 장애 발생',
    created_at: date(-45),
    updated_at: date(-1),
  },
];

// --- 배포 ---
export const mockDeployments: Deployment[] = [
  {
    id: 1,
    service_id: 1,
    deployed_by: 2,
    version: 'v1.2.3',
    commit_hash: 'a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2',
    branch: 'main',
    tag: null,
    type: 'automatic',
    status: 'success',
    started_at: date(-1),
    completed_at: date(0),
    environment: 'dev',
    rollback_from_id: null,
    notes: 'CI/CD 파이프라인을 통한 자동 배포 (칸반 기능 추가)',
    error_message: null,
    log_url: 'http://example.com/logs/1',
    created_at: date(-1),
    updated_at: date(0),
  },
  {
    id: 2,
    service_id: 1,
    deployed_by: 2,
    version: 'v1.2.2',
    commit_hash: 'f6e5d4c3b2a1f6e5d4c3b2a1f6e5d4c3b2a1f6e5',
    branch: 'main',
    tag: 'v1.2.2',
    type: 'manual',
    status: 'success',
    started_at: date(-2),
    completed_at: date(-2),
    environment: 'dev',
    rollback_from_id: null,
    notes: '핫픽스 배포 (로그인 이슈 해결)',
    error_message: null,
    log_url: null,
    created_at: date(-2),
    updated_at: date(-2),
  },
  {
    id: 3,
    service_id: 1,
    deployed_by: 2,
    version: 'v1.2.4-beta',
    commit_hash: 'b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3',
    branch: 'feat/new-feature',
    tag: null,
    type: 'manual',
    status: 'failed',
    started_at: date(0),
    completed_at: date(0),
    environment: 'dev',
    rollback_from_id: null,
    notes: '신규 기능 테스트 배포',
    error_message: '빌드 스크립트 실행 중 오류 발생: "npm run build" failed',
    log_url: 'http://example.com/logs/3',
    created_at: date(0),
    updated_at: date(0),
  },
];

// --- 대시보드 ---
export const mockDashboardStats: DashboardStats = {
  total_projects: mockProjects.length,
  active_sprints: mockSprints.filter((s) => s.status === 'active').length,
  open_issues: mockIssues.filter((i) => i.status !== 'done' && i.status !== 'closed').length,
  my_tasks: mockIssues.filter(
    (i) => i.assignee_id === 1 && i.status !== 'done' && i.status !== 'closed',
  ).length,
};
